- hosts: centos
#  strategy: debug
  vars: [
      packages_json: "{
         'version': '{{ansible_distribution_major_version}}',
         'os': '{{ansible_distribution}}',
         'package': {{packages.stdout_lines}}
       }",
  ]

  tasks:
   - name: dpkg-query
     shell: dpkg-query -W -f='${Package} ${Version} ${Architecture}\n'
     register: packages
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: rpm-query
     shell: rpm -qa
     register: packages
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

   - name: vulners-check
     uri:
      url: https://vulners.com/api/v3/audit/audit/
      return_content: yes
      method: POST
      body: "{{packages_json}}"
      body_format: json
      HEADER_Content-Type: "application/json"
     register: json_response
     when: packages
   - debug: var=json_response.json
